apiVersion: v1
kind: Service
metadata:
  name: passport-flask
  namespace: evisa-uat
spec:
  selector:
    app: passport-flask
  type: NodePort
  sessionAffinity: None
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 10800
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
    - name: passport-flask
      protocol: TCP
      port: 4322
      targetPort: 4322
      # If you set the `spec.type` field to `NodePort` and you want a specific port number,
      # you can specify a value in the `spec.ports[*].nodePort` field.
      nodePort: 31235
